[font]
size = 16.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic"}
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[window.dimensions]
columns = 133
lines = 40
