# ansible-playbook setup.yml
# mac
# Install homebrew
# Install alacritty
# brew install ansible
---
- name: Setup dev environment
  connection: local
  vars:
    git_pass: "pass"
  hosts: localhost
  tasks:
    # Need to do SSH key in ansible vault
    #- name: Create config directory
    #  ansible.builtin.file:
    #    path: ~/.config
    #    state: directory
    #    mode: '0755'
    #- name: Read-write git checkout from github
    #  ansible.builtin.git:
    #    repo: git@github.com:diablozzq/kickstart.nvim.git
    #    dest: ~/.config/nvim
  - name: Create downloads directory
    ansible.builtin.file:
      path: ~/Downloads
      state: directory
      mode: '0755'
  - name: Download neovim
    ansible.builtin.get_url:
      url: https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz
      dest: ~/Downloads/nvim-linux64.tar.gz
  - name: Create .nvim directory
    ansible.builtin.file:
      path: ~/.nvim
      state: directory
      mode: '0755'
  # Reset nvim config
  #rm -rf ~/.local/share/nvim
  #rm -rf ~/.local/state/nvim
  #rm -rf ~/.cache/nvim
  - name: Install nvim
    ansible.builtin.unarchive:
      src: ~/Downloads/nvim-linux64.tar.gz
      dest: ~/.nvim/
  - name: Install tmux
    ansible.builtin.apt:
      pkg:
        - tmux
        - make
        - gcc
        - ripgrep
        - zsh
        - npm
        - python3.10-venv
        - python3-pip
    become: true
  - name: Change user shell to zsh
    become: yes
    user:
      name: "{{ ansible_env.USER }}"
      shell: /bin/zsh
  - name: Create alacritty directory
    ansible.builtin.file:
      path: /mnt/c/Users/morla/AppData/Roaming/alacritty
      state: directory
      mode: '0755'
  - name: Download alacritty
    ansible.builtin.get_url:
      url: https://github.com/alacritty/alacritty/releases/download/v0.12.0/Alacritty-v0.12.0-portable.exe
      dest: "/mnt/c/Users/{{ ansible_user_id }}/AppData/Roaming/alacritty/alacritty.exe"
  - include: config.yml
#git config --global user.name "Kasey Morland"
#git config --global user.email "morlandkc@gmail.com"
#git config --global pull.rebase false
