---
- name: Install alacritty
  connection: local
  vars:
    alacritty_vers: "v0.13.1"
  hosts: localhost
  tasks:
    # TODO install if on linux / mac
  - name: Check if we are on Windows
    stat:
      path: /mnt/c
    register: is_windows
  - name: Create alacritty directory
    ansible.builtin.file:
      path: "/mnt/c/Users/{{ ansible_user_id }}/AppData/Roaming/alacritty"
      state: directory
      mode: '0755'
    when: is_windows.exists
  - name: Download alacritty
    ansible.builtin.get_url:
      url: "https://github.com/alacritty/alacritty/releases/download/{{ alacritty_vers }}/Alacritty-{{ alacritty_vers }}-portable.exe"
      dest: "/mnt/c/Users/{{ ansible_user_id }}/AppData/Roaming/alacritty/alacritty.exe"
    when: is_windows.exists
