---
- name: Install nerd font
  connection: local
  hosts: localhost
  tasks:
    # TODO install if on linux / mac
  - name: Check if we are on Windows
    stat:
      path: /mnt/c
    register: is_windows
  - name: Download nerd fonts
    ansible.builtin.get_url:
      url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip
      dest: "~/Downloads/"
    #when: is_windows.exists
  - name: Unarchive nerd fonts
    ansible.builtin.unarchive:
      src: ~/Downloads/JetBrainsMono.zip
      dest: ~/Downloads/JetBrainsMono
